kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: cfs-csi-node
  namespace: cubefs
spec:
  updateStrategy:
    type: OnDelete
  selector:
    matchLabels:
      app: cfs-csi-node
  template:
    metadata:
      labels:
        app: cfs-csi-node
    spec:
      serviceAccount: cfs-csi-service-account
      serviceAccountName: cfs-csi-service-account
      nodeSelector:
        "component.cubefs.io/csi": "enabled"
      containers:
        - name: csi-node-driver-registrar
          image: registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.5.0
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          args:
            - --csi-address=$(ADDRESS)
            - --kubelet-registration-path=$(DRIVER_REG_SOCK_PATH)
          env:
            - name: TZ
              value: Asia/Shanghai
            - name: ADDRESS
              value: /csi/csi.sock
            - name: DRIVER_REG_SOCK_PATH
              value: /var/lib/kubelet/plugins/csi.cubefs.com/csi.sock
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
          volumeMounts:
            - mountPath: /csi
              name: socket-dir
            - mountPath: /registration
              name: registration-dir
        - name: cfs-driver
          image: cubefs/cfs-csi-driver:v3.3.2
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          args:
            - bash
            - "-c"
            - |-
              set -e
              su -p -s /bin/bash -c "/cfs/bin/start.sh &"
              su -p -s /bin/bash -c "sleep 9999999d"
          env:
            - name: TZ
              value: Asia/Shanghai
            - name: LOG_LEVEL
              value: "5"
            - name: CSI_ENDPOINT
              value: unix:///csi/csi.sock
            - name: DRIVER_NAME
              value: csi.cubefs.com
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
          lifecycle:
            preStop:
              exec:
                command: [
                  "/bin/sh", "-c",
                  "rm -rf /csi/csi.sock"
                ]
          resources:
            requests:
              cpu: 1000m
              memory: 2Gi
          volumeMounts:
            - mountPath: /csi
              name: socket-dir
            - mountPath: /var/lib/kubelet/pods
              mountPropagation: Bidirectional
              name: mountpoint-dir
      volumes:
        - hostPath:
            path: /var/lib/kubelet/plugins/csi.cubefs.com
            type: DirectoryOrCreate
          name: socket-dir
        - hostPath:
            path: /var/lib/kubelet/plugins_registry
            type: DirectoryOrCreate
          name: registration-dir
        - hostPath:
            path: /var/lib/kubelet/pods
            type: Directory
          name: mountpoint-dir
