kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: cfs-sc-share-volume
  namespace: default
provisioner: csi.chubaofs.com
reclaimPolicy: Delete
parameters:
  # volume name can be set in two ways:
  #  1 - use pv name as volume name by default(recommended)
  #  2 - pass volume name by parameter 'volName'(not recommended)
  # volName regex pattern: "^[a-zA-Z0-9_-]{3,256}$"
  volName: "share_volume"
  # Resource manager IP address or URL
  masterAddr: "master-service.chubaofs.svc.cluster.local:17010"
  # Consul Service IP address or URL
  consulAddr: "consul-service.chubaofs.svc.cluster.local:8500"
  # Owner name as authentication
  owner: "csiuser"
  # Log levelï¼šdebug, info, warn, error
  logLevel: "debug"
  # Lookup valid duration in FUSE kernel module, unit: sec
#   lookupValid: ""
  # Attr valid duration in FUSE kernel module, unit: sec
#   attrValid: ""
  # Inode cache valid duration in client
#   icacheTimeout: ""
  # Enable DirectIO sync write, i.e. make sure data is fsynced in data node
#   enSyncWrite: ""
  # Use AutoInvalData FUSE mount option
#   autoInvalData: ""
  # Mount as read-only file system
  rdonly: "false"
  # Leverage the write cache feature of kernel FUSE. Requires the kernel FUSE module to support write cache.
#  writecache: "false"
  # Keep kernel page cache. Requires the writecache option is enabled.
#  keepcache: "false"
  authenticate: "false"
  ticketHost: ""
  enableHTTPS: "false"
  accessKey: ""
  secretKey: ""



